---
title: "Final results for NIEHS epi-stats workshop"
author: "Jenna Krall"
date: "June 15, 2015"
output: 
  html_document: 
    theme: journal
    toc: true
    numbered_sections: true
    toc_depth: 2
---


```{r setup, echo = F, message = F, warning = F}
# load knitr package 
library(knitr)

# set knitr options
opts_chunk$set(message=FALSE, echo = F,
    warning = F)
    #fig.height = 5, fig.width = 10)

```


```{r libraries}
# load necessary libraries
library(dplyr)
library(ggplot2)
library(tidyr)
library(psych)
library(MASS)
library(RColorBrewer)
library(reshape2)
library(rpart)
library(gridExtra)
library(rattle)
library(rpart.plot)
library(splines)
```


```{r opt1}
# Set options for rpart
fit.control <- rpart.control(xval = 100, cp = 0, minbucket = 5, maxcompete = 4)

# Source functions
source("niehs-epistats-fn.R")

# Set directory
opts_knit$set(root.dir = "~/Dropbox/NIEHSmixtures")


```

# Simulated dataset 1

```{r read1}
dat <- read.csv("DataSet1.csv", stringsAsFactors = F)
covar <- paste0("X", seq(1, 7))
outcome <- "Y"
confound <- "Z"

covar1 <- c(paste0("rotPC", seq(1, 4)), toupper(covar))
labels1 <- data.frame(covar1, covar1)

```


```{r sim1}
sim1 <- niehs_outer(dat, outcome, confound, covar, cp1 = 0.02, nfac = 4, labels1 = labels1)
```


# Simulated dataset 2

```{r read2}
dat <- read.csv("DataSet2.csv", stringsAsFactors = F)
covar <- paste0("x", seq(1, 14))
outcome <- "y"
confound <- "z1 + ns(z2, 3) + z3"


pc1 <- paste0("rotPC", seq(1, 6))
covar1 <- c(pc1, covar)
covar2 <- c(pc1, toupper(covar))
labels1 <- data.frame(covar1, covar2)


colnames(dat)[which(colnames(dat) %in% covar)] <- toupper(covar)
covar <- toupper(covar)
```


```{r sim2}
sim2 <- niehs_outer(dat, outcome, confound, covar, cp1 = 0.015, nfac = 6, labels1 = NULL)
```


# Real world dataset

```{r readreal}
dat <- read.csv("realdata/niehs_mix_real.csv", stringsAsFactors = F)
cn <- colnames(dat)
ss <- substr(cn, 1, 3)
covar <- cn[ss == "lip"]
outcome <- "mdi"
confound <- paste(cn[ss %in% c("chi", "mom")], collapse = "+")


# get labels

# Separate into strings/ numbers
ss1 <- strsplit(covar, "_")
type1 <- sapply(ss1, function(x) x[2])
type2 <- sapply(ss1, function(x) x[3])


# Fix PCB numbers
wh1 <- which(substr(type1, 1, 3) == "pcb") 
type2[wh1] <- substring(type1[wh1], 4)
type1[wh1] <- substr(type1[wh1], 1, 3)

# Fix DDE
type1[type1 == "pp"] <- "pp_dde" 

# Get orders
type1 <- toupper(type1)
type2 <- as.numeric(type2)
types <- data.frame(type1, type2)
ords1 <- order(types[, 1], types[, 2])

# Fix 138/158, 196/203
type2a <- sapply(ss1, function(x) x[3])
wh1 <- which(!is.na(type2a) & type1 == "PCB")
type2[wh1] <- paste0(type2[wh1], "_", type2a[wh1])


# Merge to get label
labs <- paste0(type1, "_", type2)
labs[which(is.na(type2))] <- type1[which(is.na(type2))]


# Add in rPCs
lab1 <- paste0("rotPC", seq(1, 4))

labels1 <- cbind(c(lab1, covar[ords1]), c(lab1, labs[ords1]))


# Rename dataset
colnames(dat)[colnames(dat) %in% covar] <- labs 


labels1 <- cbind(c(lab1, labs[ords1]), c(lab1, labs[ords1]))

covar <- labs
```


```{r real, fig.height = 10, fig.width = 8}
real <- niehs_outer(dat, outcome, confound, covar, cp1 = 0.023, nfac = 4, log1 = T, labels1 = labels1)
```


# Specific results for NIEHS workshop (abstract, poster, presentation)

```{r varexp}
varexp <- c(sim1$varexp, sim2$varexp, real$varexp)
varconf <- c(sim1$varconf, sim2$varconf, real$varconf)
varexp <- data.frame(c("Sim 1", "Sim 2", "Real data"), varexp, varconf)
colnames(varexp) <- c("Dataset", "% variance in exposures explained by rPCs", "% variance in y explained by confounders")
kable(varexp)
```


# Statistical significance for regression results

## Simulated dataset 1

```{r sigs}
dat1 <- sim1

dat1 <- dat1[["preg"]][["data"]]
wh1 <- which(dat1$LB > 0 | dat1$UB < 0)
dat1 <- dplyr::select(dat1, Estimate, Variable, LB, UB, Type, Group)
dat1[, c(1, 3, 4)] <- round(dat1[, c(1, 3, 4)], 2)
kable(dat1[wh1,])


```


## Simulated dataset 2



```{r sigs2}
dat1 <- sim2


dat1 <- dat1[["preg"]][["data"]]
wh1 <- which(dat1$LB > 0 | dat1$UB < 0)
dat1 <- dplyr::select(dat1, Estimate, Variable, LB, UB, Type, Group)
dat1[, c(1, 3, 4)] <- round(dat1[, c(1, 3, 4)], 2)
kable(dat1[wh1,])


```


## Real world dataset

```{r sigr}
dat1 <- real

dat1 <- dat1[["preg"]][["data"]]
wh1 <- which(dat1$LB > 0 | dat1$UB < 0)
dat1 <- dplyr::select(dat1, Estimate, Variable, LB, UB, Type, Group)
dat1[, c(1, 3, 4)] <- round(dat1[, c(1, 3, 4)], 2)
kable(dat1[wh1,])


```

# Get histograms to match C&RT output

```{r hist}

var1 <- c("X7", "X5", "X7", "X5", "X1", "X7", "X5", "X1", "X7", "X5", "X1")

var1 <- paste0("r", var1)
lt <- c("<", ">=", "<", "<", ">=", ">=", ">=", "<", ">=", "<", ">=")
val <- c(-0.41, -0.12, -0.41, -0.12, 0.26,-0.41, -0.026, 0.16, -0.41, -0.026, 0.76)
fills1 <- data.frame(var1, lt, val, seq(1, length(var1)), stringsAsFactors = F)

#seq1 <- c(1, 3, 6, 2, 4, 7, 1, 5, 8)
#fills1 <- fills1[seq1, ]

#fills1 <- data.frame(fills1, seq(1, nrow(fills1)))

cols1 <- brewer.pal(4, "Dark2")
size2 <- 10

g4a <- getden(sim1, fills1[1 : 2,], cols1, lim1 = c(-3, 3), size1 = size2)$g1


g4b <- getden(sim1, fills1[3 : 5,], cols1, lim1 = c(-3, 3), size1 = size2)$g1
g4c <- getden(sim1, fills1[6 : 8,], cols1, lim1 = c(-3, 3), size1 =size2)$g1


g4d <- getden(sim1, fills1[9 : 11,], cols1, lim1 = c(-3, 3), size1 =size2)$g1
```


# Plots for abstract, poster, presentation

```{r plot}
bcol <- brewer.pal(5, "Blues")


```



## Plots for abstract
```{r abs, eval = T}
# Combined loadings and results for simulated data1



pdf("fig1a.pdf", height = 2.5, width = 4)
sim1$pload
graphics.off()

pdf("fig1b.pdf", height = 2.5, width = 6)
sim1[["preg"]][["g1"]]
graphics.off()




pdf("fig5a.pdf", height = 1.8, width = 8)
sim2$pload
graphics.off()

pdf("fig5b.pdf", height = 2, width = 9)
sim2[["preg"]][["g1"]]
graphics.off()


pdf("fig2a.pdf", height = 2.7, width = 9)
real$pload +  theme(axis.text.x = element_text(size = 5))
graphics.off()

pdf("fig2.pdf", height = 3, width = 9)
real[["preg"]][["g1"]]
graphics.off()

pdf("fig3.pdf", height = 3, width = 9)
#fancyRpartPlot(sim1[["crt1"]])
prp(sim1[["crt1"]], branch = 1, extra = 1, box.col = bcol[1], 
    split.box.col = bcol[2], fallen.leaves = T)
graphics.off()

h1 <- 1.5
w1 <- 1.5
h2 <- 2.25
pdf("fig4a.pdf", height = h1, width = w1)
g4a
graphics.off()


pdf("fig4b.pdf", height = h2, width = w1)
g4b
graphics.off()



pdf("fig4c.pdf", height = h2, width = w1)
g4c
graphics.off()



pdf("fig4d.pdf", height = h2, width = w1)
g4d
graphics.off()

```





## Plots for poster
```{r post, eval = T}
# Combined loadings and results for simulated data

h1 <- 4
h2 <- 8
h3 <- 6


w1 <- 12
w2 <- 12



w3 <- 20
w4 <- 15
w5 <- 15

size1 <- 25
line1 <- 2


size1b <- 2
size2b <- 4.5


p1 <- "poster"
pdf(file.path(p1, "fig1a.pdf"), height = 4, width = 10)
sim1$pload  + theme(text = element_text(size = size1))
graphics.off()

pdf(file.path(p1, "fig1b.pdf"), height = 5.5, width = 10)
plot_reg_outer(sim1, size1b, size2b, line1 = F, rmun = T)  + theme(text = element_text(size = size1, line = line1))
graphics.off()




pdf(file.path(p1, "fig5a.pdf"), height = 6, width = 20)
sim2$pload  + theme(text = element_text(size = size1)) + theme(axis.text.x = element_text(size = 20))
graphics.off()

pdf(file.path(p1, "fig5b.pdf"), height = 6, width = 15)
plot_reg_outer(sim2, size1b, size2b, line1 = F, rmun = T)  + theme(text = element_text(size = size1))
graphics.off()


pdf(file.path(p1, "fig2a.pdf"), height = 6, width = 20)
real$pload  + theme(text = element_text(size = size1)) + theme(axis.text.x = element_text(size = 16))
graphics.off()

pdf(file.path(p1, "fig2.pdf"), height = 6.5, width = 17)
plot_reg_outer(real, size1b, size2b, line1 = F, rmun = T) + theme(text = element_text(size = size1))
graphics.off()



pdf(file.path(p1, "fig3.pdf"), height = h3, width = w5)
#fancyRpartPlot(sim1[["crt1"]])
prp(sim1[["crt1"]], branch = 1, extra = 1, box.col = bcol[1], 
    split.box.col = bcol[2], fallen.leaves = T, cex = 2)
graphics.off()



pdf(file.path(p1, "fig6a.pdf"), height = 6, width = 15)
#fancyRpartPlot(sim1[["crt1"]])
prp(sim2[["crt1"]], branch = 1, extra = 1, box.col = bcol[1], 
    split.box.col = bcol[2], fallen.leaves = T, cex = 2)
graphics.off()


pdf(file.path(p1, "fig6b.pdf"), height = 4, width = 15)
#fancyRpartPlot(sim1[["crt1"]])
prp(real[["crt1"]], branch = 1, extra = 1, box.col = bcol[1], 
    split.box.col = bcol[2], fallen.leaves = T, cex = 2)
graphics.off()
h1 <- 1.5
w1 <- 1.5
h2 <- 2.25

h1 <- 3
w1 <- 3
h2 <- 3 * 3/2

size1 <- 20


pdf(file.path(p1, "fig4a.pdf"), height = h1, width = w1)
g4a  + theme(text = element_text(size = size1))
graphics.off()


pdf(file.path(p1, "fig4b.pdf"), height = h2, width = w1)
g4b  + theme(text = element_text(size = size1))
graphics.off()



pdf(file.path(p1, "fig4c.pdf"), height = h2, width = w1)
g4c  + theme(text = element_text(size = size1))
graphics.off()



pdf(file.path(p1, "fig4d.pdf"), height = h2, width = w1)
g4d  + theme(text = element_text(size = size1))
graphics.off()


```


```{r real2}

p1 <- "poster"


 # Get data to plot

pca1b <- real[["pca1"]]
nc <- ncol(pca1b$scores)

# Get loadings
load <- pca1b$load[, 1 : nc]

# Find direction of maximum
dir1 <- sign(colSums(load))
load <- sweep(load, 2, dir1, "*")

# Get in format to plot
colnames(load) <- paste0("rotPC", seq(1 : nc))
mload <- melt(load)
colnames(mload)[1 : 2] <- c("variable", "PC")

# Specify colors
colsload <- c(brewer.pal(8, "Dark2"), brewer.pal(9, "Set1"),
	      brewer.pal(8, "Accent"))
# Plot
gload <- ggplot(mload, aes(x = variable, y = value, fill = variable)) +
	geom_bar(stat = "identity") + theme_bw() + theme(legend.position = "none") +
	scale_fill_manual(guide = "none", values = colsload) + xlab("") +
	ylab("Rotated PCA loadings") +
	facet_wrap(~ PC, nrow = 2) + theme(text = element_text(size = 25),
	axis.text.x = element_text(angle = 90, hjust = 1, size = 16))

pdf(file.path(p1, "fig2a.pdf"), height = 6, width = 12)
gload
graphics.off()

# Get data to plot

size1 <- 2
size2 <- 4.5




regall <- real[["preg"]][["data"]]
pd <- position_dodge(.4)

regall <- filter(regall, Type == "lm.multivar")

cols <- brewer.pal(3, "Dark2")[2 : 3]
g1 <- ggplot(regall, aes(x = Variable, y = Estimate, colour = Model, alpha = Type, shape = Type)) +
	geom_errorbar(aes(ymin = LB, ymax = UB, alpha = Type), size = size1, width = 0,
		      position = pd) +
geom_point(size = size2, width = 0,
	   position = pd) +
theme_bw() +     geom_hline(aes(yintercept = 0), size = size1, colour = "grey50",
			    linetype = "dashed") +
#geom_vline(aes(xintercept = corsx), size = size1)+
scale_color_manual(values = cols, name = "Approach", labels = c("PCA", "Exposures")) +
scale_alpha_manual(guide = F, values = c(1), labels = c( "Adjusted")) +
scale_shape_manual(values = c(16, 16), guide = "none") + xlab("") +
ylab("Change per SD increase") +
theme(text = element_text(size = 25), axis.text.y = element_text(size = 16)) +
theme(legend.position = "bottom") +
theme(axis.text.x = element_text(angle = 90, hjust = 1))

g1 <- g1 + facet_wrap(~ Group, scales = "free_x", nrow = 1)


pdf(file.path(p1, "fig2.pdf"), height = 7, width = 15)
g1
graphics.off()



```




```{r pres, eval = T}



 # Get data to plot

pca1b <- sim2[["pca1"]]
nc <- ncol(pca1b$scores)

# Get loadings
load <- pca1b$load[, 1 : nc]

# Find direction of maximum
dir1 <- sign(colSums(load))
load <- sweep(load, 2, dir1, "*")

# Get in format to plot
colnames(load) <- paste0("rotPC", seq(1 : nc))
mload <- melt(load)
colnames(mload)[1 : 2] <- c("variable", "PC")

# Specify colors
colsload <- c(brewer.pal(8, "Dark2"), brewer.pal(9, "Set1"),
	      brewer.pal(8, "Accent"))
# Plot
gload <- ggplot(mload, aes(x = variable, y = value, fill = variable)) +
	geom_bar(stat = "identity") + theme_bw() + theme(legend.position = "none") +
	scale_fill_manual(guide = "none", values = colsload) + xlab("") +
	ylab("Rotated PCA loadings") +
	facet_wrap(~ PC, nrow = 2) + theme(text = element_text(size = 22),
	axis.text.x = element_text(angle = 90, hjust = 1))

pdf("pres1.pdf", height = 6, width = 10)
gload
graphics.off()

# Get data to plot

size1 <- 2
size2 <- 5

regall <- sim2[["preg"]][["data"]]
pd <- position_dodge(.4)

cols <- brewer.pal(3, "Dark2")[2 : 3]
g1 <- ggplot(regall, aes(x = Variable, y = Estimate, colour = Model, alpha = Type, shape = Type)) +
	geom_errorbar(aes(ymin = LB, ymax = UB, alpha = Type), size = size1, width = 0,
		      position = pd) +
geom_point(size = size2, width = 0,
	   position = pd) +
theme_bw() +     geom_hline(aes(yintercept = 0), size = size1, colour = "grey50",
			    linetype = "dashed") +
#geom_vline(aes(xintercept = corsx), size = size1)+
scale_color_manual(values = cols, name = "Approach", labels = c("PCA", "Exposures")) +
scale_alpha_manual(values = c(0.5, 1), labels = c("Unadjusted", "Adjusted")) +
scale_shape_manual(values = c(16, 16), guide = "none") + xlab("") +
ylab("Change per SD increase") +
theme(text = element_text(size = 22)) +
theme(legend.position = "top") +
theme(axis.text.x = element_text(angle = 90, hjust = 1))

g1 <- g1 + facet_wrap(~ Group, scales = "free_x", nrow = 1)


pdf("pres2.pdf", height = 6.5, width = 12)
g1
graphics.off()


```
